# Generated by Django 4.1.3 on 2022-11-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="type",
            field=models.CharField(
                choices=[
                    ("question", "question"),
                    ("code", "code"),
                    ("action", "action"),
                ],
                default="question",
                max_length=32,
            ),
        ),
    ]
