# Generated by Django 4.1.3 on 2022-11-25 23:01

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_referral"),
    ]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="expire_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 28, 0, 1, 27, 660315)
            ),
        ),
    ]
