# Generated by Django 4.1.3 on 2022-11-25 23:56

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_referral_expire_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="expire_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 27, 0, 56, 52, 445831)
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="categories",
            field=models.ManyToManyField(blank=True, to="api.category"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="done_tasks",
            field=models.ManyToManyField(blank=True, to="api.task"),
        ),
    ]
