# Generated by Django 4.1.3 on 2022-11-26 00:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_config_alter_referral_expire_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterField(
            model_name="config",
            name="int_value",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="config",
            name="text_value",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="referral",
            name="expire_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 27, 1, 22, 9, 463826)
            ),
        ),
    ]
