# Generated by Django 4.1.3 on 2022-11-26 00:24

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_category_options_alter_config_int_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="config",
            name="name",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="referral",
            name="expire_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 27, 1, 24, 9, 655)
            ),
        ),
    ]
