# Generated by Django 4.1.3 on 2022-11-26 01:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_userprofile_ref_alter_referral_expire_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="expire_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 27, 2, 9, 20, 315396)
            ),
        ),
    ]
