# Generated by Django 4.1.3 on 2022-11-26 01:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_referral_expire_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="expire_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 27, 2, 14, 31, 872550)
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="ref",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.userprofile",
            ),
        ),
    ]
