# Generated by Django 4.1.3 on 2022-11-26 01:15

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_referral_expire_date_alter_userprofile_ref"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="expire_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 27, 2, 15, 2, 268653)
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.userprofile",
            ),
        ),
    ]
