# Generated by Django 4.1.3 on 2022-11-26 06:07

import datetime

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_referral_expire_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(default=True, max_length=100, null=True)),
                (
                    "answers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100), size=4
                    ),
                ),
                (
                    "rewards",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(default=1), size=4
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="referral",
            name="expire_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 27, 7, 7, 22, 509560)
            ),
        ),
    ]
