# Generated by Django 4.1.3 on 2022-11-26 06:07

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_question_alter_referral_expire_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="referral",
            name="expire_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 27, 7, 7, 50, 187170)
            ),
        ),
    ]
