# Generated by Django 4.1.3 on 2022-11-26 06:11

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_alter_question_question_alter_referral_expire_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answers",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100), null=True, size=4
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="rewards",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), null=True, size=4
            ),
        ),
        migrations.AlterField(
            model_name="referral",
            name="expire_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 27, 7, 11, 38, 653352)
            ),
        ),
    ]
