# Generated by Django 4.1.3 on 2022-11-26 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_question_answers_alter_question_rewards_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="expire_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 27, 7, 36, 29, 764219)
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="type",
            field=models.CharField(
                choices=[
                    ("question", "question"),
                    ("code", "code"),
                    ("action", "action"),
                    ("quiz", "quiz"),
                ],
                default="question",
                max_length=32,
            ),
        ),
    ]
