# Generated by Django 4.1.3 on 2022-11-26 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_alter_referral_expire_date_alter_task_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="expire_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 27, 11, 58, 33, 179613)
            ),
        ),
    ]
