version: "3.8"
services:
  postgres:
    image: "postgres:14"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=gs-careers
      - POSTGRES_USER=gs-careers
      - POSTGRES_PASSWORD=careers123
    volumes:
      - db:/var/lib/postgresql/data


volumes:
  db: